Repository AY2425S1-CS2103T-T09-1/tp, pull requests merged in 2024-11, with the labels that each got.

#129 Change result for apply, fav and unfav command
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/FavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java
  src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java
Labels: type.Task, priority.Medium, alpha-bug

#130 Change GUI colors + update screenshots
  docs/images/Ui.png
  docs/images/application shown.png
  docs/images/apply commands.png
  docs/images/applyCommand.png
  docs/images/findAppleFacebookResult.png
  docs/images/helpMessage.png
  docs/images/new company.png
  docs/images/type commands 1.png
  docs/images/updateCommand.png
  docs/images/withdrawCommand.png
  src/main/java/seedu/internbuddy/logic/commands/AddCommand.java
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/main/java/seedu/internbuddy/ui/StatusBarFooter.java
  src/main/resources/view/CompanyListCard.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/InternBuddyTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Task, severity.Low, alpha-bug, documentation-bug

#139 Update UG with overview of internbuddy
  README.md
  docs/UserGuide.md
Labels: type.Task

#140 Update DG with manual test cases
  docs/DeveloperGuide.md
Labels: type.Task

#158 Edit find parser logger name
  src/main/java/seedu/internbuddy/logic/parser/FindCommandParser.java
Labels: type.Task

#133 Format UserGuide
  docs/UserGuide.md
  docs/images/favCommand.png
  docs/images/findhardwareSWEResult.png
Labels: type.Task, priority.Medium, alpha-bug, documentation-bug

#167 EditCommand enhancements
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/main/java/seedu/internbuddy/model/company/Status.java
  src/main/java/seedu/internbuddy/model/company/StatusType.java
  src/main/java/seedu/internbuddy/model/util/SampleDataUtil.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/test/java/seedu/internbuddy/logic/LogicManagerTest.java
  src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/internbuddy/model/company/StatusTest.java
  src/test/java/seedu/internbuddy/model/company/StatusTypeTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyUtil.java
Labels: type.Enhancement

#143 Add Find Feature implementation and PUML to Developer Guide
  docs/DeveloperGuide.md
  docs/images/FindSequenceDiagram.png
Labels: type.Task, priority.Medium

#164 Make error messages more relevant
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/commands/FindCommand.java
Labels: alpha-bug

#165 Change delete success message to only show name
  src/main/java/seedu/internbuddy/logic/commands/DeleteCommand.java
  src/test/java/seedu/internbuddy/logic/commands/DeleteCommandTest.java
Labels: alpha-bug

#175 Edit JsonSerializableAddressBookTest to camelCase
  src/test/java/seedu/internbuddy/storage/JsonSerializableAddressBookTest.java
Labels: severity.VeryLow, severity.Low, alpha-bug

#172 Fix formatting error in User Guide
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#183 Add naming specifications to User Guide
  docs/UserGuide.md
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
Labels: severity.Low, alpha-bug, feature-bug, documentation-bug

#162 Add View Command
  src/main/java/seedu/internbuddy/logic/LogicManager.java
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/commands/FavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java
  src/main/java/seedu/internbuddy/logic/commands/ViewCommand.java
  src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java
  src/main/java/seedu/internbuddy/logic/parser/ViewCommandParser.java
  src/main/java/seedu/internbuddy/model/AddressBook.java
  src/main/java/seedu/internbuddy/model/Model.java
  src/main/java/seedu/internbuddy/model/ModelManager.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/main/java/seedu/internbuddy/model/company/CompanyToViewPredicate.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java
  src/test/java/seedu/internbuddy/logic/commands/AddCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/CommandTestUtil.java
  src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/ViewCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/internbuddy/model/company/CompanyToViewPredicateTest.java
  src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
Labels: type.Story, type.Task

#171 WithdrawCommand (and index based commands) Enhancements
  src/main/java/seedu/internbuddy/logic/Messages.java
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/DeleteCommand.java
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/commands/FavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java
  src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java
  src/main/java/seedu/internbuddy/logic/parser/WithdrawCommandParser.java
  src/main/java/seedu/internbuddy/model/application/Application.java
  src/test/java/seedu/internbuddy/logic/LogicManagerTest.java
  src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/WithdrawCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/WithdrawCommandParserTest.java
  src/test/java/seedu/internbuddy/model/application/ApplicationTest.java
Labels: type.Enhancement

#197 Fix compile error due to index exceed message
  src/main/java/seedu/internbuddy/logic/commands/ViewCommand.java
  src/test/java/seedu/internbuddy/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/ViewCommandTest.java
Labels: type.Bug, priority.High, severity.High

#179 Refactor and Enhance FindCommand
  src/main/java/seedu/internbuddy/logic/parser/FindCommandParser.java
  src/main/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Medium, alpha-bug, feature-bug

#181 Remove AddressBook Level-3 reference and redundant Tutorials
  docs/_markbind/layouts/default.md
  docs/site.json
Labels: priority.Medium, severity.Low, alpha-bug, documentation-bug

#189 Update Developer Guide for fav and unfav feature implementations
  docs/DeveloperGuide.md
  docs/diagrams/FavSequenceDiagram.puml
Labels: type.Task

#185 Update Developer Guide implementation for Apply and Update features
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/UpdateCommandActivity.puml
Labels: type.Enhancement, priority.Medium, severity.Low, alpha-bug, documentation-bug

#190 GUI for ViewCommand
  docs/images/Ui.png
  docs/images/favCommand.png
  docs/images/findAppleFacebookResult.png
  docs/images/findhardwareSWEResult.png
  docs/images/updateCommand.png
  docs/images/withdrawCommand.png
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/main/resources/view/InternBuddyTheme.css
Labels: type.Enhancement, type.Task, priority.Medium, priority.High, severity.Medium, severity.High, alpha-bug, feature-bug, functionality-bug, documentation-bug

#192 Add reopen command and tests
  docs/UserGuide.md
  src/main/java/seedu/internbuddy/logic/commands/ReopenCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java
  src/main/java/seedu/internbuddy/logic/parser/ReopenCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/internbuddy/logic/commands/ReopenCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/ReopenCommandParserTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/TypicalCompanies.java
  src/test/java/seedu/internbuddy/testutil/TypicalIndexes.java
Labels: type.Story, type.Enhancement, type.Task, priority.Medium, alpha-bug

#195 Add view feature into Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewSequenceDiagram.puml
Labels: type.Task

#199 Fix 1 JavaFX warning
  src/main/resources/view/InternBuddyTheme.css
Labels: type.Task, alpha-bug, feature-bug

#194 Enhance fav and unfav command for favourited and unfavourited Company
  src/main/java/seedu/internbuddy/logic/commands/FavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java
  src/test/java/seedu/internbuddy/model/company/CompanyToViewPredicateTest.java
  src/test/java/seedu/internbuddy/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/TypicalCompanies.java
Labels: alpha-bug, functionality-bug

#203 Fix output message for update command & update empty lists error messages
  src/main/java/seedu/internbuddy/logic/Messages.java
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/DeleteCommand.java
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/commands/FavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/ReopenCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java
  src/main/java/seedu/internbuddy/logic/commands/ViewCommand.java
  src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java
  src/test/java/seedu/internbuddy/logic/LogicManagerTest.java
  src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/WithdrawCommandTest.java
Labels: type.Enhancement, type.Bug

#205 Fix output errors related to AppStatus
  src/main/java/seedu/internbuddy/logic/commands/AddCommand.java
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java
  src/main/java/seedu/internbuddy/logic/parser/UpdateCommandParser.java
Labels: type.Enhancement, type.Bug

#226 Update User Guide and Developer Guide with better clarity and formatting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ApplyCommandSequence.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FavSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UpdateCommandSequence.puml
  docs/diagrams/ViewSequenceDiagram.puml
Labels: type.Bug, priority.High, severity.VeryLow, documentation-bug

#287 Add to UserGuide known issues and specifications, DeveloperGuide planned enhancements
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation-bug

#295 Improve parser package test cases
  src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/FavCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/ReopenCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/UnfavCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/ViewCommandParserTest.java
Labels: type.Enhancement

#290 Fix hyperlinks to various APIs in Developer Guide and Updating User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Bug, priority.High, severity.Low, documentation-bug

#291 Various updates to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FavSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
Labels: type.Task, documentation-bug

#300 Update UG about extra parameters and DG about edit command fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation-bug

#294 Add PHONE_NUMBER related documentation and screenshots of application
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/GUI Overview.png
  docs/images/addCommand.png
  docs/images/applyCommand.png
  docs/images/basicNoCommand.png
  docs/images/editCommand.png
  docs/images/favCommand.png
  docs/images/reopenCommand.png
  docs/images/updateCommand.png
  docs/images/withdrawCommand.png
Labels: severity.Low, feature-bug

#318 Update UML Diagrams with larger font sizes for better readability
  docs/diagrams/ApplyCommandSequence.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FavSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/UpdateCommandSequence.puml
  docs/diagrams/ViewSequenceDiagram.puml
Labels: priority.Medium

#321 Update ApplyCommandActivity UML Diagram to show status change
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ApplyCommandActivity.puml
Labels: documentation-bug

#317 UserGuide format tweaks
  docs/UserGuide.md
  docs/images/GUIOverview.png
  docs/images/applyCommand.png
  docs/images/editCommand.png
  docs/images/favCommand.png
  docs/images/sample.png
  docs/images/updateCommand.png
Labels: type.Task, documentation-bug

#319 Edits to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, documentation-bug

#323 Add Planned Enhancement regarding error messages and large inputs
  docs/DeveloperGuide.md
Labels: documentation-bug

#320 Fix more issues in DG and UG
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
Labels: type.Enhancement, documentation-bug

#326 Add Known Issue regarding Identical Applications and Planned Enhancement regarding Company Status
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation-bug

#329 Clean up user guide for submission
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#327 Add planned enhancements for duplicate
  docs/DeveloperGuide.md
Labels: documentation-bug
