Repository AY2425S1-CS2103T-T09-1/tp, pull requests merged in 2024-10, with the labels that each got.

#15 Add Qi Jun Photo
  docs/images/realqijun.png
Labels: type.Task

#16 Add photo for Erwin
  docs/images/meerkatboy.png
Labels: type.Task

#20 Update About Us Page and Portfolio for Jaymeson
  docs/AboutUs.md
  docs/team/jaymeson.md
Labels: type.Task

#21 Update Varun's portfolio and about us
  docs/AboutUs.md
  docs/team/varun.md
Labels: type.Task

#24 Update Erwin AboutUs
  docs/AboutUs.md
  docs/team/erwin.md
Labels: type.Task

#27 Update AboutUs with Simon's info
  docs/AboutUs.md
  docs/team/uniqly.md
Labels: type.Task

#26 Add AboutUs and Portfolio for Qi Jun
  docs/AboutUs.md
  docs/team/qijun.md
Labels: type.Task

#30 Fix issues in AboutUs
  docs/AboutUs.md
  docs/team/qijun.md
  docs/team/simon.md
Labels: type.Bug, severity.VeryLow

#28 Update README.md to match InternBuddy
  README.md
  docs/_markbind/layouts/default.md
  docs/images/blanklogic.png
Labels: type.Task

#31 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#33 Add UI mockup
  docs/images/Ui.png
Labels: type.Task

#41 Add Company and Status classes
  src/main/java/seedu/internbuddy/model/AddressBookCompany.java
  src/main/java/seedu/internbuddy/model/ModelCompany.java
  src/main/java/seedu/internbuddy/model/ModelManagerCompany.java
  src/main/java/seedu/internbuddy/model/ReadOnlyAddressBookCompany.java
  src/main/java/seedu/internbuddy/model/ReadOnlyUserPrefsCompany.java
  src/main/java/seedu/internbuddy/model/UserPrefsCompany.java
  src/main/java/seedu/internbuddy/model/company/Address.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/main/java/seedu/internbuddy/model/company/Email.java
  src/main/java/seedu/internbuddy/model/company/Name.java
  src/main/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicate.java
  src/main/java/seedu/internbuddy/model/company/Phone.java
  src/main/java/seedu/internbuddy/model/company/Status.java
  src/main/java/seedu/internbuddy/model/company/UniqueCompanyList.java
  src/main/java/seedu/internbuddy/model/company/exceptions/CompanyNotFoundException.java
  src/main/java/seedu/internbuddy/model/company/exceptions/DuplicateCompanyException.java
  src/main/java/seedu/internbuddy/model/util/SampleDataUtilCompany.java
  src/test/java/seedu/internbuddy/logic/commands/CommandTestUtilCompany.java
  src/test/java/seedu/internbuddy/model/AddressBookTestCompany.java
  src/test/java/seedu/internbuddy/model/ModelManagerTestCompany.java
  src/test/java/seedu/internbuddy/model/UserPrefsTestCompany.java
  src/test/java/seedu/internbuddy/model/company/AddressTest.java
  src/test/java/seedu/internbuddy/model/company/CompanyTest.java
  src/test/java/seedu/internbuddy/model/company/EmailTest.java
  src/test/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/internbuddy/model/company/NameTest.java
  src/test/java/seedu/internbuddy/model/company/PhoneTest.java
  src/test/java/seedu/internbuddy/model/company/StatusTest.java
  src/test/java/seedu/internbuddy/model/company/UniqueCompanyListTest.java
  src/test/java/seedu/internbuddy/testutil/AddressBookCompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/TypicalCompanies.java
Labels: type.Task

#45 Fix Gradle routing issues for Build
  build.gradle
Labels: type.Bug, severity.High

#58 Change Behaviour of Add Command
  src/main/java/seedu/internbuddy/logic/Messages.java
  src/main/java/seedu/internbuddy/logic/commands/AddCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/test/java/seedu/internbuddy/logic/commands/CommandTestUtil.java
  src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/internbuddy/model/company/CompanyTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
Labels: type.Task, priority.High

#54 GUI changes
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/main/java/seedu/internbuddy/ui/CompanyListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternBuddyTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#62 Add application class
  src/main/java/seedu/internbuddy/model/application/AppStatus.java
  src/main/java/seedu/internbuddy/model/application/Application.java
  src/main/java/seedu/internbuddy/model/application/Description.java
  src/main/java/seedu/internbuddy/model/application/exceptions/ApplicationNotFoundException.java
  src/main/java/seedu/internbuddy/model/application/exceptions/DuplicateApplicationException.java
  src/test/java/seedu/internbuddy/model/application/AppStatusTest.java
  src/test/java/seedu/internbuddy/model/application/ApplicationTest.java
  src/test/java/seedu/internbuddy/model/application/DescriptionTest.java
  src/test/java/seedu/internbuddy/testutil/ApplicationBuilder.java
  src/test/java/seedu/internbuddy/testutil/TypicalApplications.java
Labels: type.Task

#67 Add application list to `Company` and update storage
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/main/java/seedu/internbuddy/model/util/SampleDataUtil.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedApplication.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/internbuddy/logic/LogicManagerTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/internbuddy/model/company/CompanyTest.java
  src/test/java/seedu/internbuddy/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/TypicalCompanies.java
Labels: type.Task

#71 Improved handling of optional inputs
  src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/ParserUtil.java
  src/main/java/seedu/internbuddy/model/company/Address.java
  src/main/java/seedu/internbuddy/model/company/Phone.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/test/java/seedu/internbuddy/logic/parser/ParserUtilTest.java
  src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/CompanyUtil.java
Labels: type.Enhancement

#66 Add initial implementation of Apply Command
  src/main/java/seedu/internbuddy/logic/Messages.java
  src/main/java/seedu/internbuddy/logic/commands/AddCommand.java
  src/main/java/seedu/internbuddy/logic/commands/ApplyCommand.java
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java
  src/main/java/seedu/internbuddy/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/CliSyntax.java
  src/main/java/seedu/internbuddy/logic/parser/ParserUtil.java
  src/main/java/seedu/internbuddy/model/application/Application.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/main/java/seedu/internbuddy/model/company/Status.java
  src/main/java/seedu/internbuddy/model/name/Name.java
  src/main/java/seedu/internbuddy/model/util/SampleDataUtil.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedApplication.java
  src/main/java/seedu/internbuddy/storage/JsonAdaptedCompany.java
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/internbuddy/logic/MessagesTest.java
  src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/ParserUtilTest.java
  src/test/java/seedu/internbuddy/model/application/ApplicationTest.java
  src/test/java/seedu/internbuddy/model/application/DescriptionTest.java
  src/test/java/seedu/internbuddy/model/name/NameTest.java
  src/test/java/seedu/internbuddy/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/internbuddy/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/internbuddy/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/internbuddy/testutil/ApplicationBuilder.java
  src/test/java/seedu/internbuddy/testutil/CompanyBuilder.java
  src/test/java/seedu/internbuddy/testutil/EditCompanyDescriptorBuilder.java
  src/test/java/seedu/internbuddy/testutil/TypicalApplications.java
  src/test/java/seedu/internbuddy/testutil/TypicalCompanies.java
Labels: type.Task, priority.High

#72 Update user guide with new features
  docs/UserGuide.md
  docs/images/InterBuddyLogo.png
  docs/index.md
  docs/site.json
Labels: type.Task

#68 Add GUI for Applications + handle optional values
  docs/images/Ui.png
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/main/java/seedu/internbuddy/ui/HelpWindow.java
  src/main/resources/view/CompanyListCard.fxml
  src/main/resources/view/HelpWindow.css
Labels: type.Task

#75 Fix typo in website logo png file
  docs/UserGuide.md
  docs/images/InternBuddyLogo.png
Labels: type.Bug, severity.VeryLow

#81 Add UserGuide screenshots
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findAppleFacebookResult.png
  docs/images/helpMessage.png
Labels: type.Task

#69 Branch add applications to edit command
  src/main/java/seedu/internbuddy/logic/commands/EditCommand.java
  src/main/java/seedu/internbuddy/model/application/Application.java
  src/main/java/seedu/internbuddy/model/application/Description.java
  src/test/java/seedu/internbuddy/logic/commands/EditCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/EditCompanyDescriptorTest.java
Labels: type.Task

#86 Fix typos in website
  docs/UserGuide.md
  docs/index.md
Labels: type.Bug

#78 Modify display fields of Application
  docs/images/Ui.png
  docs/images/findAppleFacebookResult.png
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
Labels: type.Task

#88 Fix Badges in index.md
  docs/index.md
Labels: type.Bug

#96 Enable assertions in build.gradle
  build.gradle
Labels: type.Task

#101 Tweak UserGuide
  docs/UserGuide.md
  src/main/java/seedu/internbuddy/ui/CompanyListPanel.java
Labels: priority.Low

#99 Add logic to display favourited companies first
  src/main/java/seedu/internbuddy/ui/CompanyListPanel.java
Labels: type.Task

#102 UserGuide Logo Fix
  docs/UserGuide.md
Labels: type.Bug

#106 Update DG Design section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task

#111 Add initial implementation of Update command
  docs/UserGuide.md
  src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java
  src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java
  src/main/java/seedu/internbuddy/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/WithdrawCommandParser.java
  src/test/java/seedu/internbuddy/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/UpdateCommandParserTest.java
Labels: type.Task

#113 Add Apply and Update to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ApplyCommandSequence.puml
  docs/diagrams/UpdateCommandSequence.puml
Labels: type.Task

#119 Expand find to include application and tags
  src/main/java/seedu/internbuddy/logic/commands/FindCommand.java
  src/main/java/seedu/internbuddy/model/company/Company.java
  src/main/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicate.java
  src/test/java/seedu/internbuddy/model/company/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, type.Task

#116 Add favourite star thing
  src/main/java/seedu/internbuddy/ui/CompanyCard.java
  src/main/resources/images/cat.png
  src/main/resources/images/cat1.png
  src/main/resources/images/cat2.png
  src/main/resources/images/fstar.png
  src/main/resources/images/hstar.png
  src/main/resources/view/CompanyListCard.fxml
Labels: type.Story, type.Task, priority.Medium

#114 Add Favourite and Unfavourite command
  docs/UserGuide.md
  src/main/java/seedu/internbuddy/logic/commands/FavCommand.java
  src/main/java/seedu/internbuddy/logic/commands/UnfavCommand.java
  src/main/java/seedu/internbuddy/logic/parser/AddressBookParser.java
  src/main/java/seedu/internbuddy/logic/parser/FavCommandParser.java
  src/main/java/seedu/internbuddy/logic/parser/UnfavCommandParser.java
  src/test/java/seedu/internbuddy/logic/commands/FavCommandTest.java
  src/test/java/seedu/internbuddy/logic/commands/UnfavCommandTest.java
  src/test/java/seedu/internbuddy/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/FavCommandParserTest.java
  src/test/java/seedu/internbuddy/logic/parser/UnfavCommandParserTest.java
Labels: type.Story, type.Task, priority.High

#121 Add UML diagram and update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ApplyCommandActivity.puml
  src/main/java/seedu/internbuddy/ui/UiManager.java
Labels: type.Task, priority.Low

#123 Add release pictures for v1.4
  docs/images/applyCommand.png
  docs/images/updateCommand.png
  docs/images/withdrawCommand.png
Labels: type.Task, priority.High
